### ISSUE TITLE
Button doesn`t work

### ISSUE THREAD

**Issue by nomenon** [Friday14/webtorrent-desktop#2]
![image](https://user-images.githubusercontent.com/16668962/27508492-ea663792-58ee-11e7-8d55-55d208c5a8ac.png)

**Comment by em7v** [comment]
Hi my friend, I was pleasantly surprised by the open question) the fact that the now slightly not enough time for this project. And there are still too many bugs and flaws. But if you interesting I will be happy to fix these problems.

**Comment by nomenon** [comment]
This fork could be a good alternative to the popcorntimeCE

**Comment by em7v** [comment]
Now it should work)
